# Generated by Django 4.0.4 on 2022-09-21 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbaseinfo',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=1, verbose_name='状态'),
            preserve_default=False,
        ),
    ]
